apiVersion: v1
kind: Namespace
metadata:
  name: app-nginx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-deployer-role
  namespace: app-nginx
rules:
- apiGroups: ["", "apps", "networking.k8s.io"]
  resources: ["pods", "pods/log", "services", "configmaps", "secrets", "deployments", "replicasets", "ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates", "certificaterequests"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-deployer-binding
  namespace: app-nginx
subjects:
- kind: User
  name: nginx-deployer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: nginx-deployer-role
  apiGroup: rbac.authorization.k8s.io
